const router = require("express").Router();
const { protect } = require("../middleware/auth");
const { getAll, create, update, remove, toggle } = require("../controllers/recurringController");
router.use(protect);
router.get("/", getAll);
router.post("/", create);
router.put("/:id", update);
router.delete("/:id", remove);
router.patch("/:id/toggle", toggle);
module.exports = router;
