const router = require("express").Router();
const { protect } = require("../middleware/auth");
const { getAll, create, update, remove, getSummary } = require("../controllers/transactionController");
router.use(protect);
router.get("/summary", getSummary);
router.get("/", getAll);
router.post("/", create);
router.put("/:id", update);
router.delete("/:id", remove);
module.exports = router;
