import {
  FaWallet, FaChartPie, FaReceipt,
  FaChartLine, FaLock, FaMobileAlt,
} from "react-icons/fa";

export const services = [
  {
    id: "expense-tracking",
    title: "Expense Tracking",
    subtitle: "Track Every Penny, Effortlessly",
    badge: "EXPENSE TRACKING",
    desc: "Track your daily, weekly, and monthly expenses with smart categorization and real-time updates.",
    longDesc: "Smart categorization, real-time sync, and AI-powered insights let you see exactly where your money goes — daily, weekly, or monthly.",
    icon: FaWallet,
    stats: [
      { num: "20M+",  label: "Active Users" },
      { num: "4.2M",  label: "Transactions/Day" },
      { num: "34%",   label: "Avg Savings" },
      { num: "99.9%", label: "Uptime" },
    ],
    features: [
      { icon: FaWallet,    title: "Smart Categorization", desc: "AI automatically tags every transaction — groceries, dining, transport — no manual entry needed." },
      { icon: FaChartLine, title: "Real-time Updates",    desc: "See expenses reflected instantly across all your devices the moment a transaction happens." },
      { icon: FaLock,      title: "Smart Alerts",         desc: "Get notified when you're close to a budget limit or when unusual spending is detected." },
      { icon: FaChartPie,  title: "Trend Analysis",       desc: "Visual charts show your spending patterns over time so you can spot habits and cut waste." },
    ],
    steps: [
      { title: "Connect your account", desc: "Link your bank or add expenses manually in seconds." },
      { title: "Auto-categorize",      desc: "AI groups transactions automatically by category." },
      { title: "Review insights",      desc: "See daily summaries and weekly reports on your dashboard." },
      { title: "Optimize spending",    desc: "Act on AI suggestions to hit your savings targets." },
    ],
    faqs: [
      { q: "Is my financial data secure?",   a: "All data is encrypted at rest and in transit using AES-256. We never sell your data." },
      { q: "Can I track cash expenses too?", a: "Yes — you can manually add cash transactions anytime from the mobile app or dashboard." },
      { q: "Which banks are supported?",     a: "We support 10,000+ banks across 80 countries via secure Open Banking integration." },
      { q: "Is there a free plan?",          a: "Yes! Free includes unlimited manual transactions and basic categorization. Upgrade for AI insights." },
    ],
  },
  {
    id: "budget-planning",
    title: "Budget Planning",
    subtitle: "Plan Smarter, Save Better",
    badge: "BUDGET PLANNING",
    desc: "Set monthly budgets and monitor your spending habits to stay financially disciplined.",
    longDesc: "Define custom budgets for every category, get real-time progress tracking, and receive proactive alerts before you overspend.",
    icon: FaChartPie,
    stats: [
      { num: "500K+", label: "Budgets Created" },
      { num: "3x",    label: "Savings Increase" },
      { num: "89%",   label: "Goal Hit Rate" },
      { num: "12",    label: "Budget Categories" },
    ],
    features: [
      { icon: FaChartPie,  title: "Custom Categories", desc: "Create budgets for any category — dining, travel, subscriptions, and more." },
      { icon: FaReceipt,   title: "Monthly Rollover",  desc: "Unused budget rolls over to next month automatically, so nothing goes to waste." },
      { icon: FaLock,      title: "Overspend Alerts",  desc: "Get warned at 75% and 100% of each budget so you always stay on track." },
      { icon: FaChartLine, title: "AI Suggestions",    desc: "AI recommends budget amounts based on your last 3 months of spending history." },
    ],
    steps: [
      { title: "Set your income",    desc: "Enter your monthly take-home income to get started." },
      { title: "Define budgets",     desc: "Assign spending limits to each category that matters to you." },
      { title: "Track in real-time", desc: "See live progress bars update as you spend." },
      { title: "Review & adjust",    desc: "At month end, review performance and fine-tune for next month." },
    ],
    faqs: [
      { q: "Can I share a budget with my partner?", a: "Yes, household budgets can be shared with up to 5 members on the Pro plan." },
      { q: "What if I exceed my budget?",           a: "You'll get an alert and can choose to extend the budget or pause non-essential spending." },
      { q: "Does it sync with my bank?",            a: "Yes, bank transactions automatically deduct from the relevant budget category." },
      { q: "Can I set annual budgets?",             a: "Monthly and annual budgets are both supported, with quarterly breakdowns available." },
    ],
  },
  {
    id: "transaction-history",
    title: "Transaction History",
    subtitle: "Every Transaction, Crystal Clear",
    badge: "TRANSACTION HISTORY",
    desc: "View complete transaction history with advanced filtering and expense insights.",
    longDesc: "Search, filter, and export years of transaction history in seconds. Powerful tools to understand exactly how you've spent over time.",
    icon: FaReceipt,
    stats: [
      { num: "5yr",  label: "History Access" },
      { num: "50+",  label: "Filter Options" },
      { num: "3sec", label: "Avg Search Time" },
      { num: "CSV",  label: "Export Format" },
    ],
    features: [
      { icon: FaReceipt,   title: "Advanced Search",  desc: "Filter by date, merchant, category, amount range, or payment method instantly." },
      { icon: FaWallet,    title: "CSV Export",        desc: "Export any date range to CSV or PDF for accountants or tax filing." },
      { icon: FaChartPie,  title: "Custom Tags",       desc: "Add personal tags to transactions for your own tracking and notes." },
      { icon: FaMobileAlt, title: "Receipt Attach",    desc: "Snap and attach receipts to any transaction for a full paper trail." },
    ],
    steps: [
      { title: "Open History tab", desc: "Navigate to the transaction log from your dashboard." },
      { title: "Apply filters",    desc: "Filter by date, category, or merchant to narrow results." },
      { title: "View details",     desc: "Tap any transaction to see full breakdown and receipt." },
      { title: "Export",           desc: "Download filtered results as CSV or PDF in one click." },
    ],
    faqs: [
      { q: "How far back does history go?", a: "Free plan: 6 months. Pro plan: unlimited history going back to account creation." },
      { q: "Can I edit a transaction?",     a: "You can edit the category, tag, and notes. Amount and date are read-only from your bank." },
      { q: "Is export free?",               a: "Basic CSV export is free. PDF and scheduled exports are available on Pro." },
      { q: "Can I delete a transaction?",   a: "Transactions can be hidden from view but are kept for audit purposes." },
    ],
  },
  {
    id: "analytics-dashboard",
    title: "Analytics Dashboard",
    subtitle: "Your Money, Beautifully Visualized",
    badge: "ANALYTICS",
    desc: "Visualize income, savings, and expenses using beautiful charts and statistics.",
    longDesc: "Interactive charts, heat maps, and AI summaries turn your raw spending data into actionable financial intelligence.",
    icon: FaChartLine,
    stats: [
      { num: "15+",  label: "Chart Types" },
      { num: "Real", label: "Time Updates" },
      { num: "AI",   label: "Powered Insights" },
      { num: "Dark", label: "Mode Supported" },
    ],
    features: [
      { icon: FaChartLine, title: "Donut Charts",      desc: "See your spending split by category at a glance with interactive donut charts." },
      { icon: FaChartPie,  title: "Trend Lines",       desc: "Track income vs expenses over 1, 3, 6, or 12 months side by side." },
      { icon: FaReceipt,   title: "Spending Heatmap",  desc: "Calendar heatmap shows your most and least expensive days of the month." },
      { icon: FaWallet,    title: "AI Summary",        desc: "Weekly AI digest tells you what changed and what to watch in plain language." },
    ],
    steps: [
      { title: "Open Dashboard",    desc: "Your analytics home loads instantly with this week's overview." },
      { title: "Choose date range", desc: "Switch between week, month, quarter, or custom range." },
      { title: "Drill into charts", desc: "Click any chart segment to see the underlying transactions." },
      { title: "Read AI digest",    desc: "Scroll down for your personalized AI weekly financial summary." },
    ],
    faqs: [
      { q: "Can I customize my dashboard?",   a: "Yes — pin your favourite charts and reorder widgets via drag-and-drop." },
      { q: "Are charts available on mobile?", a: "Fully responsive — all charts are touch-optimized for mobile devices." },
      { q: "Can I share a report?",           a: "Generate a shareable link or PDF report from any dashboard view." },
      { q: "How often does data refresh?",    a: "Connected bank data refreshes every 4 hours; manual entries update instantly." },
    ],
  },
  {
    id: "secure-cloud-storage",
    title: "Secure Cloud Storage",
    subtitle: "Your Data, Always Safe",
    badge: "SECURITY",
    desc: "Your expense data stays protected with secure cloud synchronization and backups.",
    longDesc: "Bank-grade encryption, automatic backups, and zero-knowledge architecture ensure your financial data is yours — and only yours.",
    icon: FaLock,
    stats: [
      { num: "AES",  label: "256-bit Encryption" },
      { num: "SOC2", label: "Certified" },
      { num: "0",    label: "Data Breaches" },
      { num: "24/7", label: "Monitoring" },
    ],
    features: [
      { icon: FaLock,      title: "End-to-end Encryption", desc: "Data is encrypted on your device before it ever leaves — we can't read it even if we wanted to." },
      { icon: FaWallet,    title: "Auto Backup",            desc: "Daily automatic backups with 30-day version history so you never lose data." },
      { icon: FaMobileAlt, title: "Two-factor Auth",        desc: "Protect your account with TOTP, biometrics, or hardware keys." },
      { icon: FaChartPie,  title: "Zero-knowledge",         desc: "Your encryption keys never leave your device — true zero-knowledge architecture." },
    ],
    steps: [
      { title: "Enable 2FA",      desc: "Set up two-factor auth from Security settings for an extra layer of protection." },
      { title: "Review devices",  desc: "See all devices with access to your account and revoke any you don't recognize." },
      { title: "Set backup freq", desc: "Choose daily, weekly, or real-time backup cadence." },
      { title: "Audit log",       desc: "Review a full log of every login and data access event." },
    ],
    faqs: [
      { q: "Where is my data stored?",             a: "Data is stored in ISO 27001-certified data centres in the EU and US, with your choice of region." },
      { q: "Can Spendora employees see my data?",  a: "No — zero-knowledge encryption means your data is unreadable to anyone but you." },
      { q: "What happens if I delete my account?", a: "All data is permanently deleted within 30 days per GDPR Article 17 (right to erasure)." },
      { q: "Is Spendora GDPR compliant?",          a: "Yes — fully GDPR and CCPA compliant with a dedicated Privacy Officer." },
    ],
  },
  {
    id: "multi-device-access",
    title: "Multi Device Access",
    subtitle: "Your Finances, Everywhere You Go",
    badge: "MULTI-DEVICE",
    desc: "Access your expense tracker seamlessly from desktop, tablet, or mobile devices.",
    longDesc: "One account, every screen. Real-time sync means the moment you add an expense on your phone, it appears on your laptop instantly.",
    icon: FaMobileAlt,
    stats: [
      { num: "iOS",     label: "& Android Apps" },
      { num: "Web",     label: "Browser App" },
      { num: "<1s",     label: "Sync Speed" },
      { num: "Offline", label: "Mode Available" },
    ],
    features: [
      { icon: FaMobileAlt, title: "Native Mobile Apps", desc: "Polished iOS and Android apps with biometric login and widget support." },
      { icon: FaChartLine, title: "Web Dashboard",      desc: "Full-featured browser app — no install needed, works on any device." },
      { icon: FaReceipt,   title: "Instant Sync",       desc: "Changes sync across all devices in under one second via WebSockets." },
      { icon: FaWallet,    title: "Offline Mode",       desc: "Add expenses offline and they sync automatically when you reconnect." },
    ],
    steps: [
      { title: "Download the app", desc: "Get Spendora from the App Store or Google Play — free download." },
      { title: "Sign in",          desc: "Use your existing account — no new registration needed." },
      { title: "Enable sync",      desc: "Turn on real-time sync from Settings > Devices." },
      { title: "Work offline",     desc: "Add expenses anywhere — they sync the moment you're back online." },
    ],
    faqs: [
      { q: "How many devices can I use?",              a: "Unlimited devices on all plans — sync everywhere at no extra cost." },
      { q: "Is there a desktop app?",                  a: "A native macOS and Windows desktop app is currently in beta — sign up for early access." },
      { q: "Does offline mode work for reports?",      a: "Cached reports are available offline. Live data requires an internet connection." },
      { q: "Can I use Spendora on a shared computer?", a: "Yes — always log out when done, and use incognito mode for extra privacy." },
    ],
  },
];