// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: conversations.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversations(user_a_id, user_b_id)
VALUES($1, $2)
RETURNING id, user_a_id, user_b_id, created_at
`

type CreateConversationParams struct {
	UserAID uuid.UUID `json:"user_a_id"`
	UserBID uuid.UUID `json:"user_b_id"`
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, createConversation, arg.UserAID, arg.UserBID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.UserAID,
		&i.UserBID,
		&i.CreatedAt,
	)
	return i, err
}

const getConversationByBothUserId = `-- name: GetConversationByBothUserId :one
SELECT id, user_a_id, user_b_id, created_at FROM conversations
WHERE user_a_id = $1
  AND user_b_id = $2
`

type GetConversationByBothUserIdParams struct {
	UserAID uuid.UUID `json:"user_a_id"`
	UserBID uuid.UUID `json:"user_b_id"`
}

func (q *Queries) GetConversationByBothUserId(ctx context.Context, arg GetConversationByBothUserIdParams) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, getConversationByBothUserId, arg.UserAID, arg.UserBID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.UserAID,
		&i.UserBID,
		&i.CreatedAt,
	)
	return i, err
}

const getConversationsForUser = `-- name: GetConversationsForUser :many
SELECT
    conversations.id AS conversation_id,
    users.id AS user_id,
    users.username
FROM conversations
JOIN users
ON users.id =
    CASE
        WHEN conversations.user_a_id = $1
            THEN conversations.user_b_id
        ELSE conversations.user_a_id
    END
WHERE conversations.user_a_id = $1
   OR conversations.user_b_id = $1
`

type GetConversationsForUserRow struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	UserID         uuid.UUID `json:"user_id"`
	Username       string    `json:"username"`
}

func (q *Queries) GetConversationsForUser(ctx context.Context, userAID uuid.UUID) ([]GetConversationsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getConversationsForUser, userAID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetConversationsForUserRow{}
	for rows.Next() {
		var i GetConversationsForUserRow
		if err := rows.Scan(&i.ConversationID, &i.UserID, &i.Username); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
