// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (text, conversation_id, sender_id, sent_at)
VALUES ($1, $2, $3, $4)
RETURNING id, text, sent_at, created_at, conversation_id, sender_id
`

type CreateMessageParams struct {
	Text           string    `json:"text"`
	ConversationID uuid.UUID `json:"conversation_id"`
	SenderID       uuid.UUID `json:"sender_id"`
	SentAt         time.Time `json:"sent_at"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, createMessage,
		arg.Text,
		arg.ConversationID,
		arg.SenderID,
		arg.SentAt,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.Text,
		&i.SentAt,
		&i.CreatedAt,
		&i.ConversationID,
		&i.SenderID,
	)
	return i, err
}

const getAllMessages = `-- name: GetAllMessages :many
SELECT id, text, sent_at, created_at, conversation_id, sender_id FROM messages
`

func (q *Queries) GetAllMessages(ctx context.Context) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, getAllMessages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.Text,
			&i.SentAt,
			&i.CreatedAt,
			&i.ConversationID,
			&i.SenderID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessagesForAConversation = `-- name: GetMessagesForAConversation :many
SELECT id, text, sent_at, created_at, conversation_id, sender_id FROM messages 
WHERE messages.conversation_id = $1
`

func (q *Queries) GetMessagesForAConversation(ctx context.Context, conversationID uuid.UUID) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, getMessagesForAConversation, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.Text,
			&i.SentAt,
			&i.CreatedAt,
			&i.ConversationID,
			&i.SenderID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
