// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreateUser(ctx context.Context, username string) (User, error)
	GetAllMessages(ctx context.Context) ([]Message, error)
	GetAllUsersExceptCurrent(ctx context.Context, userAID uuid.UUID) ([]GetAllUsersExceptCurrentRow, error)
	GetConversationByBothUserId(ctx context.Context, arg GetConversationByBothUserIdParams) (Conversation, error)
	GetConversationsForUser(ctx context.Context, userAID uuid.UUID) ([]GetConversationsForUserRow, error)
	GetMessagesForAConversation(ctx context.Context, conversationID uuid.UUID) ([]Message, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
}

var _ Querier = (*Queries)(nil)
