// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"
)

type Querier interface {
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreateUser(ctx context.Context, username string) (User, error)
	GetAllMessages(ctx context.Context) ([]Message, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
}

var _ Querier = (*Queries)(nil)
