// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refresh_tokens.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createRefreshToken = `-- name: CreateRefreshToken :exec
INSERT INTO refresh_tokens (token_hash, user_id, expires_at)
VALUES ($1, $2, $3)
`

type CreateRefreshTokenParams struct {
	TokenHash string    `json:"token_hash"`
	UserID    uuid.UUID `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.ExecContext(ctx, createRefreshToken, arg.TokenHash, arg.UserID, arg.ExpiresAt)
	return err
}

const getUserByRefreshToken = `-- name: GetUserByRefreshToken :one
SELECT u.id, u.username, u.created_at FROM users u
JOIN refresh_tokens rt ON u.id = rt.user_id
WHERE rt.token_hash = $1 
  AND rt.expires_at > NOW()
  AND u.is_verified = true
`

func (q *Queries) GetUserByRefreshToken(ctx context.Context, tokenHash string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByRefreshToken, tokenHash)
	var i User
	err := row.Scan(&i.ID, &i.Username, &i.CreatedAt)
	return i, err
}

const invalidateToken = `-- name: InvalidateToken :exec
UPDATE refresh_tokens SET is_valid = FALSE WHERE token_hash = $1
`

func (q *Queries) InvalidateToken(ctx context.Context, tokenHash string) error {
	_, err := q.db.ExecContext(ctx, invalidateToken, tokenHash)
	return err
}
