// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users(username)
VALUES($1)
RETURNING id, username, created_at
`

func (q *Queries) CreateUser(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, username)
	var i User
	err := row.Scan(&i.ID, &i.Username, &i.CreatedAt)
	return i, err
}

const getAllUsersExceptCurrent = `-- name: GetAllUsersExceptCurrent :many
SELECT 
  users.id, users.username, users.created_at, 
  EXISTS (
    SELECT 1 FROM conversations
    WHERE (conversations.user_a_id = $1 AND conversations.user_b_id = users.id)
      OR (conversations.user_b_id = $1 AND conversations.user_a_id = users.id)
  ) AS is_friend
FROM users
WHERE users.id <> $1
`

type GetAllUsersExceptCurrentRow struct {
	ID        uuid.UUID `json:"id"`
	Username  string    `json:"username"`
	CreatedAt time.Time `json:"created_at"`
	IsFriend  bool      `json:"is_friend"`
}

func (q *Queries) GetAllUsersExceptCurrent(ctx context.Context, userAID uuid.UUID) ([]GetAllUsersExceptCurrentRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllUsersExceptCurrent, userAID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllUsersExceptCurrentRow{}
	for rows.Next() {
		var i GetAllUsersExceptCurrentRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.CreatedAt,
			&i.IsFriend,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, created_at FROM users
WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(&i.ID, &i.Username, &i.CreatedAt)
	return i, err
}
