import type { Document, Model, Types } from 'mongoose';
import type { TransactionType, PaymentMethod } from './transaction.constants';

// ---------------------------------------------------------------------------
// Core domain shape
// ---------------------------------------------------------------------------
export interface ITransaction {
  // Ownership — stamped at service level, never from client payload.
  userId: Types.ObjectId;

  // FK to categories collection — always required.
  categoryId: Types.ObjectId;
  categoryName: string;

  type: TransactionType;
  amount: number;
  currency: string;
  description?: string;
  paymentMethod?: PaymentMethod;

  // Flexible labels — e.g. ["vacation", "team-lunch"]
  tags?: string[];
  date: Date;

  // Whether this transaction was auto-generated by a recurrence rule.
  isRecurring: boolean;
  recurrenceId?: Types.ObjectId | null;
  // Invoice number, receipt id, or any external reference.
  referenceNote?: string;

  createdAt: Date;
  updatedAt: Date;
}

// ---------------------------------------------------------------------------
// Mongoose Document — the shape of a document returned from Mongoose queries.
// ---------------------------------------------------------------------------
export interface ITransactionDocument extends ITransaction, Document {
  _id: Types.ObjectId;
}

// ---------------------------------------------------------------------------
// Populated variant — what the API returns when category is joined.
// The populated categoryId is no longer an ObjectId; it becomes the full
// category sub-document.  Typing this separately prevents silent runtime
// mismatches in the controller/response layer.
// ---------------------------------------------------------------------------
export interface ITransactionPopulated extends Omit<ITransaction, 'categoryId'> {
  categoryId: {
    _id: Types.ObjectId;
    name: string;
    type: string;
    icon?: string;
    colorHex?: string;
  };
}

// ---------------------------------------------------------------------------
// Static methods
// ---------------------------------------------------------------------------
export interface ITransactionModel extends Model<ITransactionDocument> {
  /**
   * Calculates the net balance for a user up to a given date.
   * Used on the dashboard without fetching all transactions.
   */
  getNetBalance(
    userId: Types.ObjectId,
    toDate?: Date,
  ): Promise<{ income: number; expense: number; balance: number }>;
}

// ---------------------------------------------------------------------------
// DTO shapes
// ---------------------------------------------------------------------------

/** Payload accepted when creating a transaction. */
export interface ICreateTransactionPayload {
  // 4 required fields, rest optional
  categoryId: string;
  type: TransactionType;
  amount: number;
  currency?: string;
  description?: string;
  paymentMethod?: PaymentMethod;
  tags?: string[];
  date: Date;
  referenceNote?: string;
}

/** Payload accepted when updating a transaction (PATCH). */
export interface IUpdateTransactionPayload {
  categoryId?: string;
  categoryName?: string; // for internal use only, never from client
  amount?: number;
  description?: string;
  paymentMethod?: PaymentMethod;
  tags?: string[];
  date?: Date;
  referenceNote?: string;
}

/** Parsed + validated query parameters for transaction list endpoint. */
export interface ITransactionQuery {
  type?: TransactionType;
  categoryId?: string;
  paymentMethod?: PaymentMethod;
  startDate?: Date;
  endDate?: Date;
  minAmount?: number;
  maxAmount?: number;
  searchTerm?: string; // fuzzy match on description / referenceNote
  page?: number;
  limit?: number;
  sort?: string;
}

/** Shape returned by the paginated list service method. */
export interface ITransactionListResult {
  data: ITransactionDocument[];
  meta: {
    total: number; // total matching documents (ignoring pagination)
    page: number; // current page number
    limit: number; // items per page
    totalPages: number; // total pages available
  };
}
