import { createId } from "../utils/id.js";

function createSection(type, props = {}) {
  return {
    id: createId(),
    type,
    style: {
      paddingY: 100,
      paddingX: 32,
      maxWidth: 1200,
      background: "transparent",
      textColor: "inherit",
    },
    props,
  };
}

export const MARKETPLACE_TEMPLATES = [
  // --- FREE TEMPLATES (First 5) ---

  {
    id: "tpl-free-1",
    name: "Nexus Starter",
    slug: "nexus-starter",
    category: "SaaS",
    description: "A clean, high-conversion starter for SaaS applications.",
    isPremium: false,
    priceCents: 0,
    thumbnail: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&q=80&w=800",
    canvasData: {
      version: 1,
      sections: [
        createSection("navbar-basic", { brand: "Nexus", links: "Features,Pricing,About", cta: "Get Started" }),
        createSection("hero-saas", { title: "Ship your SaaS faster than ever.", subtitle: "The ultimate boilerplate for modern web applications built with Next.js and Tailwind." }),
        createSection("features-grid", { heading: "Everything you need" }),
        createSection("cta-banner", { heading: "Ready to build?", subheading: "Join thousands of developers shipping today." }),
        createSection("footer-basic", { brand: "Nexus" }),
      ],
    },
  },
  {
    id: "tpl-free-2",
    name: "Minimalist Dev",
    slug: "minimalist-dev",
    category: "Portfolio",
    description: "Clean and professional portfolio for software engineers.",
    isPremium: false,
    priceCents: 0,
    thumbnail: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&q=80&w=800",
    canvasData: {
      version: 1,
      sections: [
        createSection("navbar-centered", { brand: "JS.DEV", links: "Projects,Skills,Contact" }),
        createSection("hero-portfolio", { title: "I build robust digital systems.", subtitle: "Full-stack engineer specialized in distributed systems and cloud architecture." }),
        createSection("bento-grid", { heading: "Technical Arsenal" }),
        createSection("contact-form", { heading: "Let's collaborate" }),
        createSection("footer-basic", { brand: "JS.DEV" }),
      ],
    },
  },
  {
    id: "tpl-free-3",
    name: "Waitlist Alpha",
    slug: "waitlist-alpha",
    category: "Landing Page",
    description: "Convert visitors into early adopters with this simple waitlist page.",
    isPremium: false,
    priceCents: 0,
    thumbnail: "https://images.unsplash.com/photo-1551434678-e076c223a692?auto=format&fit=crop&q=80&w=800",
    canvasData: {
      version: 1,
      sections: [
        createSection("navbar-basic", { brand: "Alpha", links: "Story,Beta,FAQ" }),
        createSection("hero-saas", { title: "The next big thing is coming.", subtitle: "Be the first to experience the future of digital automation." }),
        createSection("contact-form", { heading: "Join the Waitlist", subheading: "We'll notify you when we open up early access." }),
        createSection("footer-basic", { brand: "Alpha" }),
      ],
    },
  },
  {
    id: "tpl-free-4",
    name: "Modern Writer",
    slug: "modern-writer",
    category: "Blog",
    description: "Minimalist reading experience for long-form writers and bloggers.",
    isPremium: false,
    priceCents: 0,
    thumbnail: "https://images.unsplash.com/photo-1499750310107-5fef28a66643?auto=format&fit=crop&q=80&w=800",
    canvasData: {
      version: 1,
      sections: [
        createSection("navbar-basic", { brand: "The Ledger", links: "Articles,Newsletter,About" }),
        createSection("hero-saas", { title: "Thoughtful Musings.", subtitle: "Deep dives into technology, philosophy, and the future of humanity." }),
        createSection("features-grid", { heading: "Latest Stories" }),
        createSection("cta-banner", { heading: "Subscribe", subheading: "Get weekly insights directly in your inbox." }),
        createSection("footer-basic", { brand: "The Ledger" }),
      ],
    },
  },
  {
    id: "tpl-free-5",
    name: "Corporate Base",
    slug: "corporate-base",
    category: "Marketing",
    description: "Standard professional site for established businesses and agencies.",
    isPremium: false,
    priceCents: 0,
    thumbnail: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&q=80&w=800",
    canvasData: {
      version: 1,
      sections: [
        createSection("navbar-basic", { brand: "Standard Corp", links: "Services,Clients,Contact" }),
        createSection("hero-saas", { title: "Integrity. Innovation. Impact.", subtitle: "Providing world-class consulting services for over two decades." }),
        createSection("features-grid", { heading: "Our Expertise" }),
        createSection("footer-basic", { brand: "Standard Corp" }),
      ],
    },
  },

  // --- PREMIUM TEMPLATES (Next 15) ---

  {
    id: "tpl-prem-1",
    name: "Nexus Enterprise",
    slug: "nexus-enterprise",
    category: "SaaS",
    description: "Dark-themed enterprise SaaS landing page with advanced sections.",
    isPremium: true,
    priceCents: 4900,
    thumbnail: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&q=80&w=800",
    canvasData: {
      version: 1,
      sections: [
        createSection("navbar-basic", { brand: "Nexus Pro", links: "Platform,Solutions,Pricing,Enterprise" }),
        createSection("hero-saas", { title: "The Intelligence Layer for Business.", subtitle: "Scale globally with automated infrastructure and bank-grade security." }),
        createSection("bento-grid", { heading: "Engineered for Scale" }),
        createSection("features-grid", { heading: "Core Capabilities" }),
        createSection("pricing-cards", { heading: "Enterprise Pricing" }),
        createSection("testimonials-section"),
        createSection("cta-banner", { heading: "Deploy to Nexus today." }),
        createSection("footer-basic", { brand: "Nexus Enterprise" }),
      ],
    },
  },
  {
    id: "tpl-prem-2",
    name: "Luxe E-commerce",
    slug: "luxe-ecommerce",
    category: "E-commerce",
    description: "Premium storefront for luxury brands and fashion labels.",
    isPremium: true,
    priceCents: 5900,
    thumbnail: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&q=80&w=800",
    canvasData: {
      version: 1,
      sections: [
        createSection("navbar-centered", { brand: "LUXE", links: "Collection,Shop,Stores,Journal" }),
        createSection("hero-saas", { title: "Elegance Redefined.", subtitle: "Experience the winter collection 2024. Handcrafted in Milan." }),
        createSection("features-grid", { heading: "The Artisan Way" }),
        createSection("testimonials-section"),
        createSection("cta-banner", { heading: "Shop the Collection" }),
        createSection("footer-basic", { brand: "LUXE" }),
      ],
    },
  },
  {
    id: "tpl-prem-3",
    name: "Creative Agency X",
    slug: "creative-agency-x",
    category: "Agency",
    description: "Bold and dynamic layout for creative and digital agencies.",
    isPremium: true,
    priceCents: 3900,
    thumbnail: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&q=80&w=800",
    canvasData: {
      version: 1,
      sections: [
        createSection("navbar-basic", { brand: "PULSE", links: "Works,Services,Team,Contact" }),
        createSection("hero-saas", { title: "We build digital legends.", subtitle: "Award-winning strategy and design for the world's most ambitious brands." }),
        createSection("bento-grid", { heading: "Our Services" }),
        createSection("testimonials-section"),
        createSection("contact-form", { heading: "Start a project" }),
        createSection("footer-basic", { brand: "PULSE" }),
      ],
    },
  },
  {
    id: "tpl-prem-4",
    name: "Fintech Flow",
    slug: "fintech-flow",
    category: "Startup",
    description: "Sleek and secure design for modern financial platforms.",
    isPremium: true,
    priceCents: 4500,
    thumbnail: "https://images.unsplash.com/photo-1556742044-3c52d6e88c62?auto=format&fit=crop&q=80&w=800",
    canvasData: {
      version: 1,
      sections: [
        createSection("navbar-basic", { brand: "FLOW", links: "Banking,Cards,Business,Security" }),
        createSection("hero-saas", { title: "Banking for the borderless.", subtitle: "Manage your global finances in one unified dashboard." }),
        createSection("features-grid", { heading: "Bank-grade Security" }),
        createSection("pricing-cards", { heading: "No hidden fees" }),
        createSection("cta-banner", { heading: "Open your account" }),
        createSection("footer-basic", { brand: "FLOW" }),
      ],
    },
  },
  {
    id: "tpl-prem-5",
    name: "AI Engine Pro",
    slug: "ai-engine-pro",
    category: "Startup",
    description: "Futuristic layout for AI, ML, and data science companies.",
    isPremium: true,
    priceCents: 4900,
    thumbnail: "https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&q=80&w=800",
    canvasData: {
      version: 1,
      sections: [
        createSection("navbar-basic", { brand: "NEURON", links: "Models,API,Docs,Blog" }),
        createSection("hero-saas", { title: "The Intelligence Layer.", subtitle: "Deploy large language models to production in seconds." }),
        createSection("bento-grid", { heading: "Core Capabilities" }),
        createSection("features-grid", { heading: "Built for Developers" }),
        createSection("pricing-cards", { heading: "Scalable Infrastructure" }),
        createSection("footer-basic", { brand: "NEURON" }),
      ],
    },
  },
  {
    id: "tpl-prem-6",
    name: "Analytics Hub",
    slug: "analytics-hub",
    category: "Dashboard",
    description: "Data-heavy dashboard focusing on metrics and visualizations.",
    isPremium: true,
    priceCents: 5500,
    thumbnail: "https://images.unsplash.com/photo-1551288049-bbbda536339a?auto=format&fit=crop&q=80&w=800",
    canvasData: {
      version: 1,
      sections: [
        createSection("navbar-basic", { brand: "StatsPro", links: "Overview,Users,Revenue,Settings" }),
        createSection("bento-grid", { heading: "System Health" }),
        createSection("features-grid", { heading: "Key Metrics" }),
        createSection("footer-basic", { brand: "StatsPro" }),
      ],
    },
  },
  {
    id: "tpl-prem-7",
    name: "Waitlist Ultra",
    slug: "waitlist-ultra",
    category: "Landing Page",
    description: "High-conversion waitlist page with scarcity and social proof.",
    isPremium: true,
    priceCents: 2500,
    thumbnail: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&q=80&w=800",
    canvasData: {
      version: 1,
      sections: [
        createSection("navbar-centered", { brand: "Alpha" }),
        createSection("hero-saas", { title: "Join the elite 1%.", subtitle: "Only 100 spots available for our private beta. Secure yours now." }),
        createSection("testimonials-section"),
        createSection("contact-form", { heading: "Apply for access" }),
        createSection("footer-basic", { brand: "Alpha" }),
      ],
    },
  },
  {
    id: "tpl-prem-8",
    name: "Creative Portfolio Pro",
    slug: "creative-portfolio-pro",
    category: "Portfolio",
    description: "Premium visual portfolio for designers and artists.",
    isPremium: true,
    priceCents: 3500,
    thumbnail: "https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&q=80&w=800",
    canvasData: {
      version: 1,
      sections: [
        createSection("navbar-basic", { brand: "STUDIO", links: "Work,About,Contact" }),
        createSection("hero-portfolio", { title: "Designing the Digital Future.", subtitle: "Multi-disciplinary designer focusing on high-end interaction." }),
        createSection("bento-grid", { heading: "Featured Works" }),
        createSection("testimonials-section"),
        createSection("footer-basic", { brand: "STUDIO" }),
      ],
    },
  },
  {
    id: "tpl-prem-9",
    name: "Agency Global",
    slug: "agency-global",
    category: "Agency",
    description: "Corporate agency layout for multi-national firms.",
    isPremium: true,
    priceCents: 4900,
    thumbnail: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&q=80&w=800",
    canvasData: {
      version: 1,
      sections: [
        createSection("navbar-basic", { brand: "GLOBAL", links: "Offices,Expertise,Impact,Careers" }),
        createSection("hero-saas", { title: "Expertise without borders.", subtitle: "Driving transformation for the world's leading organizations." }),
        createSection("features-grid", { heading: "Our Services" }),
        createSection("bento-grid", { heading: "Global Presence" }),
        createSection("testimonials-section"),
        createSection("footer-basic", { brand: "GLOBAL" }),
      ],
    },
  },
  {
    id: "tpl-prem-10",
    name: "Tech News Pro",
    slug: "tech-news-pro",
    category: "Blog",
    description: "Feature-rich blog layout for tech publications and news.",
    isPremium: true,
    priceCents: 2900,
    thumbnail: "https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&q=80&w=800",
    canvasData: {
      version: 1,
      sections: [
        createSection("navbar-basic", { brand: "TECHPULSE", links: "Latest,Hardware,Software,Reviews" }),
        createSection("hero-saas", { title: "The Pulse of Technology.", subtitle: "Daily updates from the bleeding edge of the silicon valley." }),
        createSection("bento-grid", { heading: "Top Stories" }),
        createSection("cta-banner", { heading: "Join the Newsletter" }),
        createSection("footer-basic", { brand: "TECHPULSE" }),
      ],
    },
  },
  {
    id: "tpl-prem-11",
    name: "LMS Master",
    slug: "lms-master",
    category: "LMS",
    description: "Educational platform layout for online courses and coaches.",
    isPremium: true,
    priceCents: 4500,
    thumbnail: "https://images.unsplash.com/photo-1501504905252-473c47e087f8?auto=format&fit=crop&q=80&w=800",
    canvasData: {
      version: 1,
      sections: [
        createSection("navbar-basic", { brand: "ACADEMY", links: "Courses,Pricing,Instructors" }),
        createSection("hero-saas", { title: "Master any skill today.", subtitle: "Learn from industry experts with our structured video courses." }),
        createSection("features-grid", { heading: "Course Curriculum" }),
        createSection("pricing-cards", { heading: "Subscription Plans" }),
        createSection("testimonials-section"),
        createSection("footer-basic", { brand: "ACADEMY" }),
      ],
    },
  },
  {
    id: "tpl-prem-12",
    name: "Mobile App Landing",
    slug: "mobile-app-landing",
    category: "Landing Page",
    description: "High-conversion landing page for mobile applications.",
    isPremium: true,
    priceCents: 3500,
    thumbnail: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?auto=format&fit=crop&q=80&w=800",
    canvasData: {
      version: 1,
      sections: [
        createSection("navbar-basic", { brand: "APPFLOW" }),
        createSection("hero-saas", { title: "Your life, in your pocket.", subtitle: "The ultimate companion for productivity and well-being." }),
        createSection("features-grid", { heading: "Intuitive Features" }),
        createSection("cta-banner", { heading: "Download on App Store" }),
        createSection("footer-basic", { brand: "APPFLOW" }),
      ],
    },
  },
  {
    id: "tpl-prem-13",
    name: "Real Estate Pro",
    slug: "real-estate-pro",
    category: "E-commerce",
    description: "Premium property listing and real estate landing page.",
    isPremium: true,
    priceCents: 4900,
    thumbnail: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&q=80&w=800",
    canvasData: {
      version: 1,
      sections: [
        createSection("navbar-basic", { brand: "ESTATE", links: "Listings,Agents,About" }),
        createSection("hero-saas", { title: "Find your dream home.", subtitle: "Exclusive properties in the world's most desirable locations." }),
        createSection("features-grid", { heading: "Our Services" }),
        createSection("contact-form", { heading: "Schedule a viewing" }),
        createSection("footer-basic", { brand: "ESTATE" }),
      ],
    },
  },
  {
    id: "tpl-prem-14",
    name: "Saas Control Panel",
    slug: "saas-control-panel",
    category: "Dashboard",
    description: "Complex management interface for SaaS administrators.",
    isPremium: true,
    priceCents: 5900,
    thumbnail: "https://images.unsplash.com/photo-1551288049-bbbda536339a?auto=format&fit=crop&q=80&w=800",
    canvasData: {
      version: 1,
      sections: [
        createSection("navbar-basic", { brand: "Control", links: "Users,Revenue,Security" }),
        createSection("bento-grid", { heading: "User Activity" }),
        createSection("pricing-cards", { heading: "Subscription Management" }),
        createSection("footer-basic", { brand: "Control" }),
      ],
    },
  },
  {
    id: "tpl-prem-15",
    name: "Final Launchpad",
    slug: "final-launchpad",
    category: "Landing Page",
    description: "High-impact final launch page with all bells and whistles.",
    isPremium: true,
    priceCents: 3900,
    thumbnail: "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&q=80&w=800",
    canvasData: {
      version: 1,
      sections: [
        createSection("navbar-basic", { brand: "LAUNCH", links: "Specs,Story,Order" }),
        createSection("hero-saas", { title: "The Future is Here.", subtitle: "Experience the most advanced technology ever built." }),
        createSection("bento-grid", { heading: "Specifications" }),
        createSection("testimonials-section"),
        createSection("cta-banner", { heading: "Secure your unit" }),
        createSection("footer-basic", { brand: "LAUNCH" }),
      ],
    },
  },
];
