import { Geist, Geist_Mono, Amarante } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const amarante=Amarante({
  variable: '--font-amrante',
  subsets: ["latin"],
  weight:'400'
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${amarante.variable} h-full antialiased`}
    >
      <body suppressHydrationWarning={true} 
      className="min-h-full flex flex-col">
        {children}
        </body>
    </html>
  );
}
